### ISSUE TITLE
img2pez does not apply prompts to images after the first one if doing several batches or higher batch numbers.

### ISSUE THREAD

**Issue by demirklvc** [ThereforeGames/unprompted#99] opened 2023-03-15 13:50 UTC
Please fix. it makes it not very usable like that.
<img width="1440" alt="Bildschirmfoto 2023-03-15 um 14 49 31" src="https://user-images.githubusercontent.com/78754525/225328969-d972abd0-7a9b-455d-aa7e-909ef8d9595d.png">

**Comment by demirklvc** [comment] 2023-03-15 13:51
@ThereforeGames

**Comment by demirklvc** [comment] 2023-03-25 16:17
yeah just ignore the issue. ......

**Comment by ThereforeGames** [comment] 2023-08-08 04:01
Duplicate of #82

**Closed as not planned by ThereforeGames** 2023-08-08 04:01 UTC
