### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by IkariDevGIT** [ThereforeGames/unprompted#4] opened 2022-11-03 12:56 UTC
if i put "Photo of a [choose]man|woman[/choose]" with the script on, nothing happens. the output is just "Photo of a [choose]man|woman[/choose]" as the prompt

**Comment by ThereforeGames** [comment] 2022-11-04 04:23
Hi, I am not able to reproduce this bug. Could you answer a few questions to help me diagnose?

- What is your Operating System?
- What version of Python are you running?
- Is your A1111 WebUI up to date?

Thanks!

**Comment by IkariDevGIT** [comment] 2022-11-04 05:33
windows, python 3.10.6, yes
side note, i use the script as an extension. you can put scripts in the extension folder, they act the same as when you put them is the script /webui folder

**Comment by ThereforeGames** [comment] 2022-11-04 06:42
Ah - there are a number of code changes required for Unprompted to function as an extension. I'm in the process of upgrading it to an extension as we speak.

**Comment by ClashSAN** [comment] 2022-11-04 06:57
When you upgrade to an extension, it no longer functions as a custom script, correct? At the very least, it won't be maintained as the script anymore. It seems the deforum script moved to an extension, and displayed a message when the script was used, stating the update. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3822

>This script is deprecated. Please use the full Deforum extension instead.
\nUpdate instructions:

**Comment by ThereforeGames** [comment] 2022-11-04 07:16
> When you upgrade to an extension, it no longer functions as a custom script, correct? 

Yes, that's correct. Old versions of Unprompted will continue to work as a script, but new versions will only be released as an extension. (I get the feeling Automatic may be trying to phase out the Script system - extensions are better in every way, as far as I can tell.)

I'll look into displaying a deprecated notification, thanks for the URL!

**Comment by ThereforeGames** [comment] 2022-11-04 07:32
Okay, Unprompted is now available as an extension! Please give the new install instructions a try and let me know if you guys run into any issues.

**EDIT:** Oh, @ClashSAN, would it be possible to migrate the Wiki entry for Unprompted to the Extensions page? I also wouldn't mind having it included on the official index if it's not asking too much. (i.e. https://raw.githubusercontent.com/wiki/AUTOMATIC1111/stable-diffusion-webui/Extensions-index.md ) Thanks!

**Closed as completed** 2022-11-05 09:21 UTC
