### ISSUE TITLE
[zoom_enhance] isn't stitching image back together

### ISSUE THREAD

**Issue by Zyin055** [ThereforeGames/unprompted#84] opened 2023-03-13 06:34 UTC
First time using this extension for the zoom_enhance feature. I noticed Dynamic Prompts extension was causing conflicts so I turned that off and restarted, which allows the zoom_enhance tag to activate. When activated, it saves the mask of the face but it doesn't stitch the image back together. I tried using the `include_original` and `save` optional arguments but neither helped.

No errors in the console.

**Comment by ThereforeGames** [comment] 2023-03-13 07:59
Hi @Zyin055,

I've seen a few reports about this on Reddit - still trying to identify the cause.

A couple ideas:

- Can you check `unprompted/lib_unprompted/stable_diffusion/clipseg` and see if you have a `weights` directory there?
- What happens if you use the `[txt2mask]` shortcode in img2img mode? For example, you can try a prompt like `[txt2mask]face[/txt2mask]walter white face`. Any errors?

Thanks!

**Comment by ThereforeGames** [comment] 2023-03-13 08:52
Hi,

I corrected a couple minor issues with the shortcode in v7.7.1. Please try updating and check if the issue persists. If it does, set `"debug":true` in `unprompted/config.json` and send me your console output - hopefully it will contain more clues. Thanks!

**Comment by dan4ik94** [comment] 2023-03-13 09:15
@ThereforeGames I have the same issue, updating to 7.7.1 didn't seem to fix it. It generates 2 identical images, however in the txt2img-images folder I can see the upscaled face as a separate 512x512 image. Attaching the log.

```Loading Unprompted v7.7.0 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Debug mode is True
(DEBUG) Loaded shortcode: ##
(DEBUG) Loaded shortcode: #
(DEBUG) Loaded shortcode: after
(DEBUG) Loaded shortcode: antonyms
(DEBUG) Loaded shortcode: array
(DEBUG) Loaded shortcode: article
(DEBUG) Loaded shortcode: autocorrect
(DEBUG) Loaded shortcode: case
(DEBUG) Loaded shortcode: casing
(DEBUG) Loaded shortcode: chance
(DEBUG) Loaded shortcode: choose
(DEBUG) Loaded shortcode: config
(DEBUG) Loaded shortcode: conjugate
(DEBUG) Loaded shortcode: do
(DEBUG) Loaded shortcode: elif
(DEBUG) Loaded shortcode: else
(DEBUG) Loaded shortcode: eval
(DEBUG) Loaded shortcode: file
(DEBUG) Loaded shortcode: filelist
(DEBUG) Loaded shortcode: for
(DEBUG) Loaded shortcode: get
(DEBUG) Loaded shortcode: hypernyms
(DEBUG) Loaded shortcode: hyponyms
(DEBUG) Loaded shortcode: if
(DEBUG) Loaded shortcode: info
(DEBUG) Loaded shortcode: length
(DEBUG) Loaded shortcode: max
(DEBUG) Loaded shortcode: min
(DEBUG) Loaded shortcode: override
(DEBUG) Loaded shortcode: pluralize
(DEBUG) Loaded shortcode: random
(DEBUG) Loaded shortcode: repeat
(DEBUG) Loaded shortcode: replace
(DEBUG) Loaded shortcode: set
(DEBUG) Loaded shortcode: sets
(DEBUG) Loaded shortcode: singularize
(DEBUG) Loaded shortcode: substring
(DEBUG) Loaded shortcode: switch
(DEBUG) Loaded shortcode: synonyms
(DEBUG) Loaded shortcode: template
(DEBUG) Loaded shortcode: unset
(DEBUG) Loaded shortcode: while
(DEBUG) Loaded shortcode: controlnet
(DEBUG) Loaded shortcode: enable_multi_images
(DEBUG) Loaded shortcode: file2mask
(DEBUG) Loaded shortcode: img2img
(DEBUG) Loaded shortcode: img2img_autosize
(DEBUG) Loaded shortcode: img2pez
(DEBUG) Loaded shortcode: init_image
(DEBUG) Loaded shortcode: instance2mask
(DEBUG) Loaded shortcode: invert_mask
(DEBUG) Loaded shortcode: pix2pix_zero
(DEBUG) Loaded shortcode: txt2mask
(DEBUG) Loaded shortcode: zoom_enhance
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading weights [c35782bad8] from C:\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV13_v13.safetensors
Applying cross attention optimization (Doggettx).
Weights loaded in 6.4s (load weights from disk: 0.3s, apply weights to model: 6.1s).
(DEBUG) Result 0: a photo of walter white standing in the desert,
(DEBUG) Entering Cleanup routine...
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:15<00:00,  1.29it/s]
(DEBUG) [scripts\unprompted.py] Entering After routine...██████████████████████████████| 20/20 [00:14<00:00,  1.35it/s]
(DEBUG) [shortcodes\stable_diffusion\zoom_enhance.py] Contour properties: 141 30 78 102
(DEBUG) [shortcodes\stable_diffusion\zoom_enhance.py] Sigmoid value: 0.988020133019603
(DEBUG) [shortcodes\stable_diffusion\zoom_enhance.py] Target size is 0.0396881103515625, denoising strength is 0.642213086462742
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:12<00:00,  1.05it/s]
Total progress: 33it [00:36,  1.10s/it]```

**Comment by ThereforeGames** [comment] 2023-03-13 09:20
@dan4ik94 Hmm, it looks like it's doing everything it's supposed to *except* updating the image in your output window.

What version of Python are you running?

**Comment by dan4ik94** [comment] 2023-03-13 09:22
> @dan4ik94 Hmm, it looks like it's doing everything it's supposed to _except_ updating the image in your output window.
> 
> What version of Python are you running?

Python 3.10.10

**Comment by ThereforeGames** [comment] 2023-03-13 09:30
I am a bit behind, on Python v3.9.7. That might be it.

Could you try the modified shortcode I've attached? It should be extracted to `unprompted/shortcodes/stable_diffusion/zoom_enhance.py`, overwriting what's already there. You will also need to restart the WebUI.

[zoom_enhance_modified.zip](https://github.com/ThereforeGames/unprompted/files/10955634/zoom_enhance_modified.zip)

The modified version appends an extra copy of the enhanced image to the output window. Curious to know if this helps.

**Comment by RenegadeX91** [comment] 2023-03-13 10:24
> I am a bit behind, on Python v3.9.7. That might be it.
> 
> Could you try the modified shortcode I've attached? It should be extracted to `unprompted/shortcodes/stable_diffusion/zoom_enhance.py`, overwriting what's already there. You will also need to restart the WebUI.
> 
> [zoom_enhance_modified.zip](https://github.com/ThereforeGames/unprompted/files/10955634/zoom_enhance_modified.zip)
> 
> The modified version appends an extra copy of the enhanced image to the output window. Curious to know if this helps.

This did the trick for me, I'm on python ver 3.10.9
This outputs the modified version with the face enhanced next to the original output in txt2img

**Comment by dan4ik94** [comment] 2023-03-13 15:24
Working fine with `use_workaround`

**Comment by jhlchu** [comment] 2023-03-13 19:11
`use_workaround` stitches it back together but in the output folder of txt2img it only shows the original, doesn't save. Img2img folder just contains a bunch of faces. Can't find the folder where it outputs the final stitched image. `save` and `include_original` are both on.

**Comment by MrKuenning** [comment] 2023-03-13 19:14
> `use_workaround` stitches it back together but in the output folder of txt2img it only shows the original, doesn't save. Img2img folder just contains a bunch of faces. Can't find the folder where it outputs the final stitched image. `save` and `include_original` are both on.

Same for me, checking this box, shows the corrected image in my webUI, but it does not save to the output folder.
I also have a bunch of errors in the console when this script runs.

I am on Python 3.10.6

```
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 5 required positional arguments: 'ti_keywords', 'keyword_order', 'lora_model', 'lora_multiplier', and 'lora_keywords'

Error running process: E:\AI\A1111\extensions\sd-webui-cutoff\scripts\cutoff.py
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 8 required positional arguments: 'enabled', 'targets_', 'weight', 'disable_neg', 'strong', 'padding', 'intp', and 'debug'

Error running process_batch: E:\AI\A1111\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 427, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\AI\A1111\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 169, in process_batch
    if not args[0]:
IndexError: tuple index out of range
```

These do not show up in the console, if the exact same prompt is run without the zoom_enhance portion.

**Comment by jhlchu** [comment] 2023-03-13 19:32
@MrKuenning It's incompatible with a lot of extensions. I had to turn off many to get the errors to go away. It appears `sd-webui-cutoff` and `sd-webui-additional-networks` are the issue in your case.

**Comment by MrKuenning** [comment] 2023-03-13 21:16
I disabled both of those extensions but I still get this error:


`TypeError: Script.process() missing 5 required positional arguments: 'ti_keywords', 'keyword_order', 'lora_model', 'lora_multiplier', and 'lora_keywords'`

**Comment by ManOrMonster** [comment] 2023-03-13 21:52
For me, it's saving the stiched images in my custom temp folder, which I've set in my webui-user.bat:

set TEMP=C:\\stable-diffusion\\stable-diffusion-webui\\tmpgens
set TMP=C:\\stable-diffusion\\stable-diffusion-webui\\tmpgens

**Comment by joedemo42** [comment] 2023-03-14 12:52
Neither the zip file nor the newer version with use_workaround do anything for me. I have pretty much every extension disabled. Whatever I do, i only ever get the original image back.The face does get saved to img2img folder, and when I use the option, I get the mask, the face and the other intermediate image in my webui folder. Just no stitched image. I‘m using NoCrypts Colab v23-03-11A. https://colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq

**Comment by joedemo42** [comment] 2023-03-14 20:13
I kinda fixed it for me. Seems like explicitly setting a temp directory when launching stable-diffusion-webui did the trick.
At the bottom of the notebook that I use, my WebUI is now launched like this:
`!mkdir /content/sd-temp `
`!COMMANDLINE_ARGS="{commandline_arguments}" REQS_FILE="requirements_versions.txt" TEMP="/content/sd-temp" python launch.py`

The last one is one line. Using this, I get shown the original and the zoom_enhanced image in the WebUI
Still have to run it with `use_workaround`, or it doesn’t stitch the final image. Also, it only saves the final image in the temp folder.
I remember reading somewhere, that the python version was suspected of causing this. I‘m running Python 3.9.16

**Comment by MrKuenning** [comment] 2023-03-14 21:37
After updating the extension, I no longer get any errors in the console.  But the merged image is still not saved to my output folder.  When I enable the work around, I see it side by side with the pre merged image, but my output folder does not save the final image.

It does however save the debug image, even though I don't have that option selected in my command.

**Comment by glenndav** [comment] 2023-03-23 02:20
Confirmed, I'm seeing the same thing as MrKurenning.

**Comment by 311-code** [comment] 2023-04-01 01:37
I am on newest automatic1111 and using the shortcode to replace face. It used to work using a fix posted here a couple weeks ago. Now I got a new PC and it doesn't stitch together the images after it renders the face, it puts the new face render in img2img folder only.

**Comment by 311-code** [comment] 2023-04-05 04:18
Update: I was able to fix this using the use_workaround option in the prompt, example: [after]{zoom_enhance use_workaround replacement="woman's face"}

Now it stitches the face on. Hope this helps someone.

**Comment by ThereforeGames** [comment] 2023-04-23 05:40
Hi all,

As of v8.2.0, I believe `use_workaround` is no longer necessary. I finally got around to updating my Python environment to 3.10 and can confirm that `[zoom_enhance]` works without any special workaround. :)

**Closed as completed by ThereforeGames** 2023-04-23 05:40 UTC
